using LLVMSharp.Interop;
using Mug.Generator.TargetGenerators.C;
using Mug.Generator.IR;
using Mug.Lexer;
using Mug.Parser;
using Mug.Parser.AST;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace Mug.Compilation
{
    public class CompilationUnit : CompilerComponent
    {
        public static readonly string[] AllowedExtensions = new[] { ".mug" };

        public bool FailedOpeningPath { get; } = false;
        public string[] Paths { get; }

        private static string ClangFilename
        {
            get
            {
                if (Environment.OSVersion.Platform is PlatformID.Win32NT)
                    return "C:/Program Files/LLVM/bin/clang.exe";
                else
                    return "/usr/bin/clang";
            }
        }

        public CompilationUnit(string outputFilename, params string[] paths) : base(new(outputFilename))
        {
            Paths = paths;
        }

        public void CompileLLVMIR(int optimizazioneLevel, string output, bool onlyBitcode, string optionalFlag)
        {
            var e = GenerateLLVMIR(out var llvmmodule);
            PrettyPrinter.PrintAlerts(e);

            if (!HasErrors())
                WriteLLVMModule(optimizazioneLevel, output, onlyBitcode, optionalFlag, llvmmodule);
        }

        public void CompileC(int optimizazioneLevel, string output, string optionalFlag)
        {
            var e = GenerateC(out var ccode);
            PrettyPrinter.PrintAlerts(e);

            if (!HasErrors())
                WriteCModule(optimizazioneLevel, output, optionalFlag, ccode);
        }

        private void WriteLLVMModule(
            int optimizazioneLevel, string output, bool onlyBitcode, string optionalArgs, LLVMModuleRef llvmmodule)
        {
            var bitcode = Path.ChangeExtension(Tower.OutputFilename, "bc");

            // deletes a possible file named in the same way as the result, to avoid bugs in the while under
            if (File.Exists(bitcode)) File.Delete(bitcode);
            if (File.Exists(output)) File.Delete(output);

            // writes the module to a file
            if (llvmmodule.WriteBitcodeToFile(bitcode) != 0)
                CompilationTower.Throw("Error writing to file");

            if (onlyBitcode) return;

            // the program goes in this keeps the program waiting until it finds the file containing the compiled program
            while (!File.Exists(bitcode) || File.Exists(output))
                ;

            // clang compiler
            CallCompilerFromShell($"clang", $"{bitcode} -o {output} {optionalArgs}", optimizazioneLevel);

            // deletes the bytecode file, now remains only the executable generated by clang
            if (File.Exists(bitcode)) File.Delete(bitcode);
        }

        private static void WriteCModule(
            int optimizazioneLevel, string output, string optionalArgs, string ccode)
        {
            var cfile = GetTempCachePath();
            if (File.Exists(cfile)) File.Delete(cfile);

            File.WriteAllText(cfile, ccode);

            while (!File.Exists(cfile))
                ;

            CallCompilerFromShell($"gcc", $"{cfile} -o {Path.GetFullPath(output)} -nostdlib {optionalArgs}", optimizazioneLevel);
        }

        private static string GetTempCachePath()
        {
            return Path.ChangeExtension(Path.GetTempFileName(), "c");
        }

        public bool HasErrors()
        {
            return Tower.HasErrors();
        }

        public static void CallCompilerFromShell(string compiler, string args, int optimizazioneLevel)
        {
            // checks the clang execuatble exists
            if (!File.Exists(ClangFilename))
                CompilationTower.Throw($"Cannot find the clang executable at: '{ClangFilename}'");

            // call clang
            var clang = Process.Start(
                new ProcessStartInfo
                {
                    FileName = compiler,
                    Arguments = $"-O{optimizazioneLevel} {args}",
                    // invisible window
                    CreateNoWindow = true,
                    UseShellExecute = false,
                    ErrorDialog = false,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                });

            // the program will wait until clang works
            clang.WaitForExit();
            if (clang.ExitCode != 0)
            {
                var output = clang.StandardOutput.ReadToEnd();

                if (string.IsNullOrEmpty(output))
                    output = clang.StandardError.ReadToEnd();

                CompilationTower.Throw($"External compiler: {output}");
            }
        }

        private void InternalGenerateAST()
        {
            foreach (var path in Paths)
            {
                if (!File.Exists(path))
                    CompilationTower.Throw($"Invalid path '{path}'");

                if (!AllowedExtensions.Contains(Path.GetExtension(path)))
                    continue;

                var subtower = new CompilationTower(path);
                (subtower.Lexer = new(Path.GetFileNameWithoutExtension(path), File.ReadAllText(path), subtower)).Tokenize();

                var head = subtower.Parser.Parse();

                Tower.Types.AddRange(subtower.Types);
                Tower.Parser.Module.Members.AddRange(head.Members);
                Tower.Diagnostic.AddRange(subtower.Diagnostic);
            }
        }

        private void InternalGenerateTAST()
        {
            InternalGenerateAST();
            Tower.TAST = Tower.Solver.Solve();
        }

        private void InternalGenerateMIR()
        {
            InternalGenerateTAST();
            Tower.MIRModule = Tower.Generator.Generate();
        }

        private void InternalGenerateLLVMIR()
        {
            InternalGenerateMIR();
            if (!HasErrors())
                Tower.LLVMModule = (LLVMModuleRef)Tower.TargetGenerator.Lower();
        }

        private void InternalGenerateC()
        {
            InternalGenerateMIR();
            if (!HasErrors())
                Tower.CModule = (string)Tower.TargetGenerator.Lower();
        }

        private CompilationException GenerateCatched(Action action)
        {
            CompilationException result;

            try { action(); result = new(Tower.Diagnostic); }
            catch (CompilationException e) { result = e; }

            return result;
        }

        public CompilationException GenerateAST(out NamespaceNode head)
        {
            var result = GenerateCatched(InternalGenerateAST);
            head = Tower.AST;
            return result;
        }

        public CompilationException GenerateTAST(out NamespaceNode head)
        {
            var result = GenerateCatched(InternalGenerateTAST);
            head = Tower.TAST;
            return result;
        }

        public CompilationException GenerateIR(out MIR ir)
        {
            var result = GenerateCatched(InternalGenerateMIR);
            ir = Tower.MIRModule;
            return result;
        }

        public CompilationException GenerateLLVMIR(out LLVMModuleRef ir)
        {
            var result = GenerateCatched(InternalGenerateLLVMIR);
            ir = Tower.LLVMModule;
            return result;
        }

        public CompilationException GenerateC(out string code)
        {
            Tower.SetGenerator(new CGenerator(Tower));
            var result = GenerateCatched(InternalGenerateC);
            code = Tower.CModule;
            return result;
        }
    }
}
