using LLVMSharp.Interop;
using Mug.Models.Generator.IR;
using Mug.Models.Lexer;
using Mug.Models.Parser;
using Mug.Models.Parser.AST;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace Mug.Compilation
{
    public class CompilationUnit : MugComponent
    {
        public static readonly string[] AllowedExtensions = new[] { ".mug" };

        public bool FailedOpeningPath { get; } = false;
        public string[] Paths { get; }

        private static string ClangFilename
        {
            get
            {
                if (Environment.OSVersion.Platform == PlatformID.Win32NT)
                    return "C:/Program Files/LLVM/bin/clang.exe";
                else
                    return "/usr/bin/clang";
            }
        }

        public CompilationUnit(string outputFilename, params string[] paths) : base(new(outputFilename))
        {
            Paths = paths;
        }

        public void Compile(int optimizazioneLevel, string output, bool onlyBitcode, string optionalFlag)
        {
            // generates the bytecode
            GenerateMIR();

            CompileModule(optimizazioneLevel, output, onlyBitcode, optionalFlag);
        }

        /// <summary>
        /// writes the llvm module to a file and calls the llvm compiler on it
        /// </summary>
        private void CompileModule(int optimizazioneLevel, string output, bool onlyBitcode, string optionalFlag)
        {
            /*writeFile(
                IRGenerator.Module,
                optimizazioneLevel,
                Path.ChangeExtension(IRGenerator.Parser.Lexer.ModuleName, "bc"),
                output,
                onlyBitcode,
                optionalFlag);

            static void nothing()
            {
                // called to avoid misunderstanding while reading the code
            }

            /// writes the bytecode to a file, calls clang on it and deletes the bytecode file
            static void writeFile(LLVMModuleRef module, int optimizazioneLevel, string bitcode, string output, bool onlyBitcode, string optionalFlag)
            {
                // deletes a possible file named in the same way as the result, to avoid bugs in the while under
                if (File.Exists(bitcode)) File.Delete(bitcode);
                if (File.Exists(output)) File.Delete(output);

                // writes the module to a file
                if (module.WriteBitcodeToFile(bitcode) != 0)
                    PrettyPrinter.Throw("Error writing to file");

                if (onlyBitcode) return;

                // the program goes in this keeps the program waiting until it finds the file containing the compiled program
                while (!File.Exists(bitcode) || File.Exists(output)) nothing();

                // clang compiler
                CallClang($"{bitcode} -o {output} {optionalFlag}", optimizazioneLevel);

                // deletes the bytecode file, now remains only the executable generated by clang
                if (File.Exists(bitcode)) File.Delete(bitcode);
            }*/
        }

        /*public static void CallClang(string command, int optimizazioneLevel)
        {
            // checks the clang execuatble exists
            if (!File.Exists(ClangFilename))
                PrettyPrinter.Throw($"Cannot find the clang executable at: '{ClangFilename}'");

            // call clang
            var clang = Process.Start(
                new ProcessStartInfo
                {
                    FileName = ClangFilename,
                    Arguments = $"-O{optimizazioneLevel} {command}",
                    // invisible window
                    CreateNoWindow = true,
                    UseShellExecute = false,
                    ErrorDialog = false,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                });

            // the program will wait until clang works
            clang.WaitForExit();
            if (clang.ExitCode != 0)
            {
                var output = clang.StandardOutput.ReadToEnd();

                if (output == "")
                    output = clang.StandardError.ReadToEnd();

                PrettyPrinter.Throw($"External compiler: {output}");
            }
        }*/

        public void GenerateAST()
        {
            foreach (var path in Paths)
            {
                if (!File.Exists(path))
                    CompilationTower.Throw($"Invalid path '{path}'");

                // only mug files
                if (!AllowedExtensions.Contains(Path.GetExtension(path)))
                    continue;

                var subtower = new CompilationTower(path);
                (subtower.Lexer = new MugLexer(Path.GetFileNameWithoutExtension(path), File.ReadAllText(path), subtower)).Tokenize();

                var head = subtower.Parser.Parse();

                Tower.Types.AddRange(subtower.Types);
                Tower.Parser.Module.Members.Nodes.AddRange(head.Members.Nodes);
                Tower.Diagnostic.AddRange(subtower.Diagnostic);
            }
        }

        public NamespaceNode GenerateTAST()
        {
            GenerateAST();
            return Tower.Solver.Solve();
        }

        public MIR GenerateMIR()
        {
            GenerateTAST();
            return Tower.Generator.Generate();
        }
    }
}
